name = "CircuitSim"
uuid = "d23419fb-c42c-4a7b-bf83-7ff8eeedf333"
version = "0.0.1"
authors = ["Erik Buer <buer94@gmail.com>"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "^1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "GLMakie"]
