name = "CircuitTypes"
uuid = "d23419fb-c42c-4a7b-bf83-7ff8eeedf333"
version = "0.0.1"
authors = ["Erik Buer <buer94@gmail.com>"]

[deps]


[compat]
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[targets]
test = ["Test", "Documenter", "CairoMakie"]
