name = "CircuitTypes"
uuid = "d23419fb-c42c-4a7b-bf83-7ff8eeedf333"
authors = ["Erik Buer <buer94@gmail.com>"]
version = "0.0.1"

[deps]


[compat]
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]