[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
CircuitSim = "d23419fb-c42c-4a7b-bf83-7ff8eeedf333"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
