name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.11'] # , 'nightly'
        julia-arch: [x64, x86]
        os: [ubuntu-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      
      - name: Install qucsator_rf dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix gperf flex bison cmake
      
      - name: Build and install qucsator_rf
        run: |
          git clone https://github.com/ra3xdh/qucsator_rf.git
          cd qucsator_rf
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build build --config Release
          sudo make -C build install
          cd ..
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: xvfb-run -s '-screen 0 1024x768x24'